/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author igo2
 */
public class Genio extends javax.swing.JFrame {

    /**
     * Creates new form Genio
     */
     /** Iniciando o construtor com a frase do Gênio  */
    public Genio() {
        initComponents();
        lblTextoGenio.setText("<html>Vou pensar em um valor entre 1 e 1.000.000, tente advinhar!<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnPalpite = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        lblImagemGenio = new javax.swing.JLabel();
        lblTextoGenio = new javax.swing.JLabel();
        lblMensagemBalao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spnPalpite.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        spnPalpite.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000000, 1));
        getContentPane().add(spnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 160, 50));

        btnPalpite.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 160, 80));

        lblImagemGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/imagens/genio.png"))); // NOI18N
        lblImagemGenio.setText("jLabel1");
        getContentPane().add(lblImagemGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 397, 400));

        lblTextoGenio.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblTextoGenio.setText("jLabel1");
        getContentPane().add(lblTextoGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 330, 240));

        lblMensagemBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/imagens/balaodafrase.png"))); // NOI18N
        getContentPane().add(lblMensagemBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Metodo para gerar o número aleatorio
     e em seguida testar para ver se os números são iguais */
    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
       int numGenio = (int)(Math.random() * 1000000 ) + 1;
       
       int palpiteUsuario = Integer.parseInt(spnPalpite.getValue().toString());
       
       if(numGenio == palpiteUsuario){
           lblTextoGenio.setText("ACERTOU");
       }else{
           lblTextoGenio.setText("<html>Eu pensei no númeoro: " + numGenio + "<html>");
       }
       
       //lblTextoGenio.setText(palpiteUsuario == numGenio ? "ACERTOU": "<html>Eu pensei no númeoro: " + numGenio + "<html>");
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel lblImagemGenio;
    private javax.swing.JLabel lblMensagemBalao;
    private javax.swing.JLabel lblTextoGenio;
    private javax.swing.JSpinner spnPalpite;
    // End of variables declaration//GEN-END:variables
}
