/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

import javax.swing.JOptionPane;

/**
 *
 * @author igo2
 */

/**
 * Classe RepeticaoSlider que cria uma interface gráfica para controlar uma contagem
 * usando sliders para definir o início, o fim e o passo da contagem.
 */
public class RepeticaoSlider extends javax.swing.JFrame {

    /**
     * Creates new form RepeticaoSlider
     */
    
      /**
     * Construtor que inicializa os componentes da interface
     * e define os valores iniciais dos labels.
     */
    public RepeticaoSlider() {
        initComponents();
        lblInicio.setText(Integer.toString(sldInicio.getValue()));
        lblFim.setText(Integer.toString(sldFim.getValue()));
        lblPasso.setText(Integer.toString(sldPasso.getValue()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sldInicio = new javax.swing.JSlider();
        sldFim = new javax.swing.JSlider();
        sldPasso = new javax.swing.JSlider();
        lblTextoInicio = new javax.swing.JLabel();
        lblTextoFim = new javax.swing.JLabel();
        lblTextoPasso = new javax.swing.JLabel();
        btnContar = new javax.swing.JButton();
        lblInicio = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        lblPasso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sldInicio.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        sldInicio.setMaximum(99);
        sldInicio.setValue(0);
        sldInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldInicioStateChanged(evt);
            }
        });

        sldFim.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        sldFim.setMinimum(1);
        sldFim.setValue(8);
        sldFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFimStateChanged(evt);
            }
        });

        sldPasso.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        sldPasso.setMaximum(50);
        sldPasso.setMinimum(1);
        sldPasso.setValue(1);
        sldPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPassoStateChanged(evt);
            }
        });

        lblTextoInicio.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTextoInicio.setText("Inicio");

        lblTextoFim.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTextoFim.setText("Fim");

        lblTextoPasso.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTextoPasso.setText("Passo");

        btnContar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btnContar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade05/imagens/contador.png"))); // NOI18N
        btnContar.setText("Contar ");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });

        lblInicio.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblInicio.setText("Inicio");

        lblFim.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblFim.setText("Fim");

        lblPasso.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblPasso.setText("Passo");

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTextoInicio)
                                .addGap(18, 18, 18)
                                .addComponent(sldInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTextoFim)
                                        .addGap(27, 27, 27)
                                        .addComponent(sldFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTextoPasso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sldPasso, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblInicio)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFim)
                                    .addComponent(lblPasso))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnContar)
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextoInicio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sldFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextoFim))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sldPasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextoPasso)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInicio)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim)
                        .addGap(18, 18, 18)
                        .addComponent(lblPasso)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnContar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     /**
     * Método chamado quando o slider de início é alterado.
     * Atualiza o label de início e ajusta os valores máximos do slider de passo.
     *
     */
    
    private void sldInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldInicioStateChanged
        // TODO add your handling code here:
       //Pega os valores de inicio e fim 
        int inicio = sldInicio.getValue();
        int fim = sldFim.getValue();

        /**
         * Compara se o início é maior que o fim 
         * caso seja, faz a alteração no fim.
          */
        if (inicio >= fim) {
            fim = inicio + 1;
            sldFim.setValue(fim); 
        }
        /** 
         * Mostra o valor de inicio e define o número máximo de passos
         */
        lblInicio.setText(Integer.toString(inicio));
        int maxPasso = Math.max(fim - inicio, 1);
        sldPasso.setMaximum(maxPasso);
        
    }//GEN-LAST:event_sldInicioStateChanged
    
     /**
     * Método chamado quando o slider de fim é alterado.
     * Atualiza o label de fim e ajusta os valores máximos do slider de passo.
     */
    private void sldFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFimStateChanged
        // TODO add your handling code here:
        int inicio = sldInicio.getValue();
        int fim = sldFim.getValue();
        
        /**
         * Compara se o fim é menor que o começo, caso seja, altera o inicio
         */
        if (fim <= inicio) {
            inicio = fim - 1;
            sldInicio.setValue(inicio); 
        }
        /** 
         * Mostra o valor de inicio e define o número máximo de passos
         */
        
        lblFim.setText(Integer.toString(fim));
        int maxPasso = Math.max(fim - inicio, 1);
        sldPasso.setMaximum(maxPasso);
        
    }//GEN-LAST:event_sldFimStateChanged
    
    /**
     * Método chamado quando o slider de passo é alterado.
     * Atualiza o label de passo conforme o valor selecionado.
     */
    private void sldPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPassoStateChanged
        // TODO add your handling code here:
        int passo = sldPasso.getValue();
        lblPasso.setText(Integer.toString(passo));
    }//GEN-LAST:event_sldPassoStateChanged
    
    /**
     * Esse método é acionado quando o butão btnContar é clicado 
     */
    
    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        // TODO add your handling code here:
        
        /**
         * Obtém os valores atuais dos três sliders (início, fim, passo).
         */
        
        int inicio = sldInicio.getValue();
        int fim = sldFim.getValue();
        int passo = sldPasso.getValue();
        
        /**
         * impa o conteúdo atual da área de texto antes de exibir a nova contagem.
         */
        txtArea.setText("");
        
       /**
        * Impressão dos números no text area
        */
        for(int i = inicio; i <= fim; i = i + passo){
           txtArea.append(i + "\n");
        }
        
    }//GEN-LAST:event_btnContarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepeticaoSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepeticaoSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepeticaoSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepeticaoSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepeticaoSlider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPasso;
    private javax.swing.JLabel lblTextoFim;
    private javax.swing.JLabel lblTextoInicio;
    private javax.swing.JLabel lblTextoPasso;
    private javax.swing.JSlider sldFim;
    private javax.swing.JSlider sldInicio;
    private javax.swing.JSlider sldPasso;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
